[package]
name = "rs-service"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web.workspace= true
serde_json.workspace = true
serde.workspace = true
rs-primitives = { path = "../rs-primitives" }
rs-dispatcher = { path = "../rs-dispatcher" }