[package]
name = "rs-onchain"
version.workspace = true
edition.workspace = true

[dependencies]
serde_json.workspace = true
serde.workspace = true
rs-strategy = { path = "../rs-strategy" }
rs-primitives = { path = "../rs-primitives" }
rs-psql = { path = "../rs-psql" }